#pragma once
#include"wx/wx.h"

enum MainWin
{
	MAINWIN = wxID_LOWEST + 32,
	MAINWINGAME,
	LINEUPCHANGE,
	STARTNEWSEASON
};

enum TeamWin
{
	TEAMWIN = STARTNEWSEASON + 1,
	TEAMNAME,
	TEAMWINPANEL,
	LEFTTITLE,
	RIGHTTITLE,
	CHANGELINEUP,
	LWING1,
	CENTER1,
	RWING1,
	LWING2,
	CENTER2,
	RWING2,
	LWING3,
	CENTER3,
	RWING3,
	LWING4,
	CENTER4,
	RWING4,
	LEFTDEF1,
	RIGHTDEF1,
	LEFTDEF2,
	RIGHTDEF2,
	LEFTDEF3,
	RIGHTDEF3,
	GOALIE
};

enum ListViewWin
{
	LISTVIEWID = GOALIE + 1,
	ALLPLAYRSBUTTON,
	FORWARDSBUTTON,
	DEFENSEBUTTON,
	GOALIEBUTTON
};

enum CustomControl
{
	CUSTOMWIN = ListViewWin::GOALIEBUTTON + 1
};

enum class GameWindow
{
	GAMEWIN = CustomControl::CUSTOMWIN + 1,
	BIT_TEAM_AWAY_IMAGE,
	BIT_TEAM_HOME_IMAGE,
	AWAY_RECORD,
	HOME_RECORD,
	AWAY_RECORD_WINS,
	AWAY_RECORD_LOSSES,
	AWAY_RECORD_OVERTIME_LOSSES,
	HOME_RECORD_WINS,
	HOME_RECORD_LOSSES,
	HOME_RECORD_OVERTIME_LOSSES,
	AWAYSHOTS,
	HOMESHOTS,
	AWAYSCORE,
	HOMESCORE,
	MESSAGE_UPDATE,
	GAMEOVER,
	OVERTIME,
	REBOUND, 
	FREEZ, 
	GOAL_ALLOWED
};

enum TeamSelectWindow
{
	TEAMSELECTWIN = CustomControl::CUSTOMWIN + 24
};

enum LineupChangeWin
{
	LINEUPCHANGEWIN = TeamSelectWindow::TEAMSELECTWIN,
	SEARCHBUTTON
};

enum StartSeasonWin
{
	STARTSEASONWIN = LineupChangeWin::SEARCHBUTTON + 1
};

enum SeasonStatsWindow
{
	SEASONSTATSWIN = StartSeasonWin::STARTSEASONWIN
};

enum class BracketlegPosition
{
	BRACKET_HORIZONTAL = SeasonStatsWindow::SEASONSTATSWIN,
	BRACKET_VER,
	BRACKET_LEFT,
	BRACKET_RIGHT,
	BRACKET_FIRST_ROUND,
	BRACKET_SECOND_ROUND_BOTTOM,
	BRACKET_SECOND_ROUND_TOP,
	BRACKET_THIRD_ROUND_TOP,
	BRACKET_THIRD_ROUND_BOTTOM,
	BRACKET_FOURTH_ROUND
};

enum class PlayoffSeriesPair
{
	CENTRAL_FIRST = SEASONSTATSWIN + 11,
	CENTRAL_SECOND,
	PACIFIC_FIRST, 
	PACIFIC_SECOND,
	ATLANTIC_FIRST,
	ATLANTIC_SECOND,
	METROPOLITAN_FIRST,
	METROPOLITAN_SECOND,
	CENTRAL_SECOND_ROUND,
	PACIFIC_SECOND_ROUND,
	ATLANTIC_SECOND_ROUND,
	METROPOLITAN_SECOND_ROUND,
	WESTERN_THIRD_ROUND,
	EASTERN_THIRD_ROUND,
	STANLEY_CUP_ROUND
};
